#!/bin/bash
# This script intercepts Docker commands to strip the --user flag
# for compatibility with Sysbox environments.

declare -a args
skip_next=false
fix_user=false

for arg in "$@"; do
  if [ "$skip_next" = true ]; then
    skip_next=false
    continue
  fi

  case "$arg" in
  --user=* | -u=*)
    # Matches --user=1000 or -u=1000
    fix_user=true
    continue
    ;;
  --user | -u)
    # Matches --user 1000 or -u 1000 (skips the next value)
    fix_user=true
    skip_next=true
    continue
    ;;
  *)
    args+=("$arg")
    ;;
  esac
done

# Execute the original docker binary with the filtered arguments
start_time=$(date +%s)
/usr/bin/docker "${args[@]}"
exit_code=$?

# Fix root-owned files created during this docker run, in select directories
if ((EUID != 0)) && [[ $fix_user == true && $PWD != "$HOME" ]]; then
  echo "[xndv] fixing file permissions..."

  owner="$(id -u):$(id -g)"

  fix_perms() {
    find "$1" -mindepth 1 -maxdepth "$2" \
      -newermt "@${start_time}" -user root \
      -printf '[xndv] chown -R %p\n' \
      -exec sudo chown -R "$owner" {} + \
      -prune 2>/dev/null
  }

  fix_perms "$HOME" 2
  fix_perms "$PWD" 5
  fix_perms /tmp 3

  echo "[xndv] ...fixed file permissions"
fi

exit $exit_code
